spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tag?useSSL=false
    username: root
    password: password

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect