spring:
# Application Settings
  application:
    name: tag-backend

# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3306/tag?useSSL=false
    username: root
    password: password

# JPA Settings
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: true