spring:
# Application Settings
  application:
    name: tag-backend

# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3333/tag?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

# JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: true