spring:
# Application Settings
  application:
    name: tag-backend

# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3333/tag?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

# JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: true
    database: mysql

  # Cache Settings
  cache:
    type: redis
    cache-names: tag

# Redis Settings
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 3000
      lettuce:
        pool:
          max-active: 5
          max-wait: -1
          max-idle: 8
          min-idle: 0
